// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afdgiwuweggbtgtduhvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmZGdpd3V3ZWdnYnRndGR1aHZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY1ODEyNTYsImV4cCI6MjEwMjE1NzI1Nn0.BbsnYvCxoN3NkHkfVaGMIMZkmOnJF__EaesMwuojhJE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});